version: "3.9"

services:
  frontend:
    container_name: react-app
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /frontend
    command: npm start
    image: node:latest
    
    ports:
      - 3000:3000

    environment:
      - CHOKIDAR_USEPOLLING=true
    
